### ISSUE TITLE
Honeycomb vs App "version" in package.json

### ISSUE THREAD

**Issue by celstark** [brown-ccv/neuro-task-starter#312]
Issue: We should have separate honeycomb and "our app" version / name / etc. info in package.json

Currently, the honeycomb package.json lists a "version" that helps us track what version of honeycomb we based our own apps on. As we build our own apps, though, that version, name, author, etc. info migrates from honeycomb-specific to our own apps' info so that we can track our own app's development.  Not only does this then lead to conflicts when we try to update honeycomb within our own app, but tracking down things like "just which release of honeycomb did I base this on??" gets more challenging than it should.

Solution: Have both a "version" and a "honeycomb_version" key in package.json.  For the main honeycomb, these would be the same, but for apps built on it, they would differ.

**Comment by RobertGemmaJr** [comment]
We are currently working on building Honeycomb into it's own package which would solve this issue in a larger/better capacity.

It is possible to determine which version of Honeycomb you're using based on the git sha at the start of your repository. Is this something you need assistance in? Updating Honeycomb after creating the new repository is not something we work with much (again, current work is being done on this) but if you have specific questions let us know

**Comment by celstark** [comment]
Thanks.  I did the merge yesterday and just added in my own key to keep things clear for the next time. I was thinking that having honeycomb and your sample app code separate (the 3.2 shuffle of things into the App folder helped in that way) -- the main honeycomb would .gitignore the App folder as one option but it seems you're solidly working on what's likely a cleaner plan there.

At the moment, the issues are just on getting things packaged properly for others to use as stand-alone.  The main offender is the Mac, getting it to build for both arm64 and x64 and dealing with Apple's security. In a former life I dealt with that, so I'm at least familiar with some of the issues.

**Comment by RobertGemmaJr** [comment]
Yeah, we're hoping to separate the deployment logic, react app, and JsPsych timeline into separate packages/libraries. Most labs want to keep our react app but the more modular the better. 

RE the mac issues I would give this script a shot:
```json
"package:mac": "npm run package -- --arch universal --targets @electron-forge/maker-dmg"
```

It's not fully tested yet but that should solve the architecture issue.

**Comment by RobertGemmaJr** [comment]
The security is a whole other can of worms, we believe it has to do with code signage that the [Electron documentation](https://www.electronjs.org/docs/latest/tutorial/tutorial-packaging#important-signing-your-code) may be able to help you out with.

**Comment by celstark** [comment]
Yup - on both of those.  So far, no joy with a similar approach (package:mac-intel and package:mac with different archs), but I've hunted down those / similar links to work on.  IIRC there as an @electron/universal to include as well. I'm still hoping that the app can go out without signing as my Apple Dev account has expired.  I'll update here with progress if it works.

**Comment by celstark** [comment]
Just as an FYI as it's not really on-topic for this thread, but changing the `--arch x64` to `--arch universal` in package:mac does build things as universal binaries.  The app itself is a fat (`lipo -detailed_info` shows as such with both arm64 and x64), the frameworks are all fat, and even the little helper apps in there are all fat.  Everything looks good, but we still fail to launch on an Intel mac when built on Apple Silicon.  We get an uncaught exception saying it's only finding arm64 and needs x86_64h.  The only parseable aspect in there is pointing to issues in Contents/Resources/app.asar/node_nodules/bindings/bindings.js and Contents/Resources/app.asar/node_modules/@serialport/bindings/lib/darwin.js

**Comment by RobertGemmaJr** [comment]
You've convinced me! I add a `honeycomb_version` field in #317 and add instructions on how to fill it out in the documentation. Will definitely be helpful in the short term. Thanks!

**Comment by RobertGemmaJr** [comment]
>  but we still fail to launch on an Intel mac when built on Apple Silicon. We get an uncaught exception saying it's only finding arm64 and needs x86_64h. The only parseable aspect in there is pointing to issues in Contents/Resources/app.asar/node_nodules/bindings/bindings.js and Contents/Resources/app.asar/node_modules/@serialport/bindings/lib/darwin.js

Does running the built app from the GitHub release have the same issues?

`@serialport` is needed for communicating to EEG machines (we're trying to move towards Electron's [API](https://www.electronjs.org/docs/latest/tutorial/devices#web-serial-api) but it's been a time). If that's not something you need you could remove the functions from `public/electron.js` and that dependency

**Comment by celstark** [comment]
I shifted this into a new report, #318 to keep things clean and, yes, it happens in the built app from the repo.

**Comment by RobertGemmaJr** [comment]
Closing as the original issue is complete in #317
